language: android
android:
  components:
      # The BuildTools version used by your project
      - build-tools-28.0.3
      # The SDK version used to compile your project
      - android-28
      # Additional components
      - extra-android-m2repository

branches:
  only:
    - dev
    - master

notifications:
  email: false

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
#install: ./gradlew clean build
script: ./gradlew check